// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Help = require("./Help.bs.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var DiscordJs = require("discord.js");
var ConfigJson = require("../config.json");

console.log("Hello, BuckleScript and Reason!");

var token = ConfigJson.token;

var client = new DiscordJs.Client();

client.on("ready", (function (param) {
        console.log("Bot is ready");
        client.user.setActivity("Proving spyder doesn't know discord");
        return /* () */0;
      }));

client.on("message", (function (msg) {
        var match = msg.author.bot;
        var match$1 = msg.content.indexOf("!");
        var match$2 = msg.channel.name;
        var exit = 0;
        if (match) {
          if (match$2 === "spyder-reasonml") {
            return /* () */0;
          } else {
            exit = 1;
          }
        } else if (match$1 !== 0 || match$2 !== "spyder-reasonml") {
          exit = 1;
        } else {
          console.log("Handling command", msg.content);
          var msg$1 = msg;
          var command = Belt_List.fromArray(msg$1.content.substr(1).split(" "));
          if (command) {
            switch (command[0]) {
              case "help" : 
                  msg$1.reply(Help.help(command[1]));
                  return /* () */0;
              case "ping" : 
                  msg$1.reply("pong");
                  return /* () */0;
              default:
                return /* () */0;
            }
          } else {
            return /* () */0;
          }
        }
        if (exit === 1) {
          console.log("Unhandled message from", msg.author.username, "in Channel", msg.channel.name, "Contents '" + (msg.content + "'"));
          return /* () */0;
        }
        
      }));

client.login(token);

/*  Not a pure module */
