// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");

var swearRegexStr = $$String.concat("|", /* :: */[
      "fuck",
      /* :: */[
        "shit",
        /* :: */[
          "cunt",
          /* :: */[
            "arse",
            /* [] */0
          ]
        ]
      ]
    ]);

function spiders(x) {
  if (x !== 0) {
    return ":spider:" + spiders(x - 1 | 0);
  } else {
    return "";
  }
}

var partial_arg = new RegExp(swearRegexStr, "ig");

function filterMessage(param) {
  return param.replace(partial_arg, (function (match_, param, param$1) {
                return match_.charAt(0) + spiders(match_.length - 1 | 0);
              }));
}

function swears(msg) {
  var content = msg.content;
  var censoredMessage = Curry._1(filterMessage, content);
  if (censoredMessage !== content) {
    console.log("Filtering message", content);
    var channel = msg.channel;
    var author = msg.author.username;
    channel.send("**" + (String(author) + ("**: " + (String(censoredMessage) + ""))));
    msg.delete();
    return /* () */0;
  } else {
    return 0;
  }
}

exports.swears = swears;
/* swearRegexStr Not a pure module */
