// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function help(param) {
  if (param) {
    switch (param[0]) {
      case "calc" : 
          return "Not implemented";
      case "help" : 
          return "\n!**help**:\n\nShows information on available commands.\n\n\n\n``!help [command]``\n\n\n\n``[command]`` *(optional)*: the name of a command";
      default:
        return "I don't know how to help with that";
    }
  } else {
    return "Commands:\nhelp\ncalc\nbanana";
  }
}

exports.help = help;
/* No side effect */
