// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Os = require("os");
var Process = require("process");
var DiscordJs = require("discord.js");

var release = Os.release();

var uptime = Os.uptime() / 86400 | 0;

var totalmem = Os.totalmem() / 1073741824 | 0;

var freemem = Os.freemem() / 1073741824 | 0;

var info = "\nOS codename: " + (String(Process.platform) + (" version " + (String(release) + ("\nUptime: " + (String(uptime) + (" days\nMemory: " + (String(freemem) + (" / " + (String(totalmem) + " GB\nStorage: plenty 😂\n")))))))));

console.log("sys info", info);

function richInfo(param) {
  return new DiscordJs.RichEmbed().setTitle("Spyder's bot hosting system").setColor("DARK_PURPLE").setDescription(info);
}

var secondsPerDay = 86400;

var bytesPerGB = 1073741824;

exports.release = release;
exports.secondsPerDay = secondsPerDay;
exports.uptime = uptime;
exports.bytesPerGB = bytesPerGB;
exports.totalmem = totalmem;
exports.freemem = freemem;
exports.info = info;
exports.richInfo = richInfo;
/* release Not a pure module */
